# Server Configuration
server.port=${PORT:8080}
spring.application.name=dochive-backend

# Datasource / PostgreSQL (Supabase) Configuration
spring.datasource.url=${SUPABASE_DB_URL}
spring.datasource.username=${SUPABASE_DB_USER}
spring.datasource.password=${SUPABASE_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Spring AI - Gemini AI Configuration
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.model=gemini-3.1-flash-lite
# Embedding Configuration
spring.ai.google.genai.embedding.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.embedding.text.model=gemini-embedding-001
spring.ai.google.genai.embedding.text.dimensions=1536

# Multipart Upload Limits
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB

# Custom Properties for PORTFOLIO Ingestion
portfolio.data.source-path=${RESUME_DOC_PATH:classpath:docs/resume-portfolio.md}
tesseract.datapath=${TESSDATA_PREFIX:/usr/share/tesseract-ocr/5/tessdata/}

# Actuator Configuration
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.info.env.enabled=true

# Actuator Info Endpoint Details
info.app.name=RAG Ingestion pipeline backend for 2 strategies: DOCHIVE and PORTFOLIO
info.app.description=Document Knowledge Base & RAG Backend
info.app.version=1.0.0
info.app.owner=Aman Saxena

# Swagger / SpringDoc OpenAPI Configuration
springdoc.api-docs.path=/v1/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tags-sorter=alpha